Added bengali langauage
jmoiron/humanize pull request #221
Opened 2021-07-29 16:28 UTC by wasi-master

Adds the language called [Bengali](https://en.wikipedia.org/wiki/Bengali_language) with is spoken by [Bengalis](https://en.wikipedia.org/wiki/Bengalis) and [60 others according to google](https://www.google.com/search?q=bengali+language+spoken+by) that mostly live in [Bangladesh](https://en.wikipedia.org/wiki/Bangladesh) and [Kolkata](https://en.wikipedia.org/wiki/Kolkata)

The language is spoken by approximately 228 million native speakers and another 37 million as second-language speakers and [ranks 7th](https://www.visualcapitalist.com/100-most-spoken-languages) among the most spoken languages in the world

2021-07-30 10:22 UTC, hugovk requested changes
Thanks for the PR! Please can you update these couple of things, and add the language to the README list? https://github.com/jmoiron/humanize#humanize

2021-07-30 10:22 UTC, hugovk commented on src/humanize/locale/bn_BD/LC_MESSAGES/humanize.po
> +"Content-Type: text/plain; charset=ASCII\n"
We'll need UTF-8 here: 
```suggestion
"Content-Type: text/plain; charset=UTF-8\n"
```

2021-07-30 10:22 UTC, hugovk commented on src/humanize/locale/bn_BD/LC_MESSAGES/humanize.po
> +"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"
And we'll need the correct values in here.

2021-08-01 10:26 UTC, hugovk commented on src/humanize/locale/bn_BD/LC_MESSAGES/humanize.po
> +"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"
Please replace `INTEGER` and `EXPRESSION`

See https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html which has examples for other language families.

2021-08-01 10:29 UTC, hugovk commented on src/humanize/locale/bn_BD/LC_MESSAGES/humanize.po
> +"Project-Id-Version: PACKAGE VERSION\n"
This is the name and version of the package.

You can do something like one of the other language files: 

```
src/humanize/locale/ca_ES/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/de_DE/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/es_ES/LC_MESSAGES/humanize.po:"Project-Id-Version: \n"
src/humanize/locale/fa_IR/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/fi_FI/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/fr_FR/LC_MESSAGES/humanize.po:"Project-Id-Version: PROJECT VERSION\n"
src/humanize/locale/id_ID/LC_MESSAGES/humanize.po:"Project-Id-Version: \n"
src/humanize/locale/it_IT/LC_MESSAGES/humanize.po:"Project-Id-Version: \n"
src/humanize/locale/ja_JP/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/ko_KR/LC_MESSAGES/humanize.po:"Project-Id-Version: PROJECT VERSION\n"
src/humanize/locale/nl_NL/LC_MESSAGES/humanize.po:"Project-Id-Version: PROJECT VERSION\n"
src/humanize/locale/pl_PL/LC_MESSAGES/humanize.po:"Project-Id-Version: 0.0.1\n"
src/humanize/locale/pt_BR/LC_MESSAGES/humanize.po:"Project-Id-Version: \n"
src/humanize/locale/pt_PT/LC_MESSAGES/humanize.po:"Project-Id-Version: \n"
src/humanize/locale/ru_RU/LC_MESSAGES/humanize.po:"Project-Id-Version: PROJECT VERSION\n"
src/humanize/locale/sk_SK/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/sl_SI/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/sv_SE/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/tr_TR/LC_MESSAGES/humanize.po:"Project-Id-Version: humanize\n"
src/humanize/locale/uk_UA/LC_MESSAGES/humanize.po:"Project-Id-Version: PROJECT VERSION\n"
src/humanize/locale/vi_VN/LC_MESSAGES/humanize.po:"Project-Id-Version: PROJECT VERSION\n"
src/humanize/locale/zh_CN/LC_MESSAGES/humanize.po:"Project-Id-Version: 1.0\n"
```

2021-08-01 15:58 UTC, wasi-master commented
okay I resolved all the issues

2021-08-01 19:07 UTC, hugovk approved these changes

2021-08-01 19:07 UTC, merged

2021-08-01 19:14 UTC, hugovk commented
Thank you, released in 3.11.0!

2021-08-01 19:47 UTC, wasi-master commented
:)

2021-08-01 19:49 UTC, wasi-master commented
Wait I forgot to add the language to readme.md

2021-08-01 20:46 UTC, hugovk commented
No problem, I'll do it!