Documentation improvements
jmoiron/humanize pull request #254
Opened 2022-02-22 19:49 UTC by mondeja

Changes proposed in this pull request:

* Fix `clamp()` arguments not being correctly rendered with `mkdocstrings`.
* Use [`include-markdown`](https://github.com/mondeja/mkdocs-include-markdown-plugin#mkdocs-include-markdown-plugin) Mkdocs plugin to include "Usage" section of README inside Home.
* Don't allow to select `>>>` text nodes inside codeblocks. For `pycon` code blocks uses [the recipe suggested by mkdocstrings](https://mkdocstrings.github.io/recipes/#prevent-selection-of-in-python-code-blocks) and for `python` codeblocks a Javascript function with a CSS class.

2022-02-27 13:11 UTC, hugovk requested changes
Thank you very much for this, nice improvements! 

---

> * Don't allow to select `>>>` text nodes inside codeblocks. For `pycon` code blocks uses [the recipe suggested by mkdocstrings](https://mkdocstrings.github.io/recipes/#prevent-selection-of-in-python-code-blocks) and for `python` codeblocks a Javascript function with a CSS class.

I'm not sure if this is working?

For example, at `/number/#humanize.number.clamp`, when I click the "Copy to clipboard icon", it copies this:

```
>>> clamp(123.456)
'123.456'
>>> clamp(0.0001, floor=0.01)
'<0.01'
>>> clamp(0.99, format="{:.0%}", ceil=0.99)
'99%'
>>> clamp(0.999, format="{:.0%}", ceil=0.99)
'>99%'
>>> clamp(1, format=intword, floor=1e6, floor_token="under ")
'under 1.0 million'
>>> clamp(None) is None
True
```

Should it instead copy something like this?

```
clamp(123.456)
clamp(0.0001, floor=0.01)
clamp(0.99, format="{:.0%}", ceil=0.99)
clamp(0.999, format="{:.0%}", ceil=0.99)
clamp(1, format=intword, floor=1e6, floor_token="under ")
clamp(None) is None
```

2022-02-27 13:11 UTC, hugovk commented on README.md
> +```python
Let's keep `pycon` for these with Python console output:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/1324225/155883429-c2903baa-eae6-4552-b1e8-7f4e94f104b6.png">

https://pygments.org/docs/lexers/#pygments.lexers.python.PythonConsoleLexer

2022-02-27 13:11 UTC, hugovk commented on docs/css/code_select.css
> +/* >>> selection in ```python``` code blocks is handled with Javascript */
```suggestion
/* >>> selection in ```python``` code blocks is handled with JavaScript */
```

2022-03-01 11:52 UTC, pawamoy commented
We should probably use `pycon` for code blocks detected in examples, and provide the CSS rule to prevent selection of `>>>` and `...` by default in mkdocstrings :slightly_smiling_face:

2022-03-01 18:52 UTC, mondeja commented
> when I click the "Copy to clipboard icon", it copies this...

Opened an issue in [mkdocs-material#3647](https://github.com/squidfunk/mkdocs-material/issues/3647) and seems that the unique solution would be to hide the "Copy to clipboard" buttons.

I've pinned `pymdown-extensions>=9.2` because the function `pygments_lang_class` has been included in that version. Also updated the CSS selectors to only target `pycon` codeblocks.

2022-03-01 18:56 UTC, pawamoy commented
I didn't know about that pygment option, I'm not sure how to include these CSS rules by default in the new Python handler now :confused:

2022-03-01 19:30 UTC, mondeja commented
> Maybe we shouldn't include them by default, as pointed out in the issue you opened.

I agree, what do you think @hugovk?

2022-03-05 20:02 UTC, hugovk commented
Sure, fine to disable it.

The [Sphinx version of the copy button](https://sphinx-copybutton.readthedocs.io/) can strip out `>>>` but I understand if it's too complex for mkdocs-material to implement. We don't have all that much code examples here.

Thanks!

2022-03-06 08:26 UTC, hugovk approved these changes

2022-03-06 08:27 UTC, merged

2022-03-06 08:27 UTC, hugovk commented
Thanks!